version: "3"
services:
  node:
    build: ./tools/node
    container_name: node
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 3000:3000
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true