version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.29
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    container_name: mysql
    environment:
      MYSQL_DATABASE: chat_app
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./tools/mysql/initdb.d:/docker-entrypoint-initdb.d
