version: '3'
services:
  python3:
    restart: always
    build: ./tools/python
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
    ports: 
      - 8000:8000