version: '3'
services:
  mysql:
    build: ./tools/mysql
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: chat_app
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
